apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
      version: v1
  template:
    metadata:
      labels:
        app: product-catalog
        version: v1
    spec:
      containers:
      - name: product-catalog
        image: thallavi/product-catalog:1608189357bd9a6b7c1f105bc48e00ccebe4fd05
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_HOST
          value: "ecommerce-mongo"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: "products_db"


---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: ecommerce
spec:
  ports:
  - port: 3001
    name: http
  selector:
    app: product-catalog
