apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-inventory
      version: v1
  template:
    metadata:
      labels:
        app: product-inventory
        version: v1
    spec:
      containers:
      - name: product-inventory
        image: thallavi/product-inventory:1608189357bd9a6b7c1f105bc48e00ccebe4fd05
        ports:
        - containerPort: 3002
        env:
        - name: POSTGRES_HOST
          value: "ecommerce-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "inventory_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"


---
apiVersion: v1
kind: Service
metadata:
  name: product-inventory
  namespace: ecommerce
spec:
  ports:
  - port: 3002
    name: http
  selector:
    app: product-inventory
