apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-and-handling
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-and-handling
      version: v1
  template:
    metadata:
      labels:
        app: shipping-and-handling
        version: v1
    spec:
      containers:
      - name: shipping-and-handling
        image: thallavi/shipping-and-handling:1608189357bd9a6b7c1f105bc48e00ccebe4fd05
        ports:
        - containerPort: 8080
        env:
        - name:  MONGO_URI
          value:  mongodb://ecommerce-mongo:27017/shipping_handling

---
apiVersion: v1
kind: Service
metadata:
  name: shipping-and-handling
  namespace: ecommerce
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: shipping-and-handling
