name: CI - Build and Push Microservices

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_HUB_USER: thallavi
  DOCKER_HUB_REPO_PREFIX: thallavi
  # Optional tag can be dynamic, e.g., use GITHUB_SHA or latest
  IMAGE_TAG: latest

jobs:
  build-and-push:
    name: Build & Push Changed Microservices
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (for better build caching and multi-arch)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Determine changed directories (for optimization)
      - name: Detect changed services
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ecommerce-ui:
              - 'ecommerce-ui/**'
            product-catalog:
              - 'product-catalog/**'
            product-inventory:
              - 'product-inventory/**'
            order-management:
              - 'order-management/**'
            shipping-and-handling:
              - 'shipping-and-handling/**'
            profile-management:
              - 'profile-management/**'
            contact-support-team:
              - 'contact-support-team/**'

      # 5. Build & push only changed images
      - name: Build and push ecommerce-ui
        if: steps.changes.outputs.ecommerce-ui == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./ecommerce-ui
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USER }}/ecommerce-ui:${{ env.IMAGE_TAG }}

      - name: Build and push product-catalog
        if: steps.changes.outputs.product-catalog == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./product-catalog
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USER }}/product-catalog:${{ env.IMAGE_TAG }}

      - name: Build and push product-inventory
        if: steps.changes.outputs.product-inventory == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./product-inventory
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USER }}/product-inventory:${{ env.IMAGE_TAG }}

      - name: Build and push order-management
        if: steps.changes.outputs.order-management == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./order-management
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USER }}/order-management:${{ env.IMAGE_TAG }}

      - name: Build and push shipping-and-handling
        if: steps.changes.outputs.shipping-and-handling == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./shipping-and-handling
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USER }}/shipping-and-handling:${{ env.IMAGE_TAG }}

      - name: Build and push profile-management
        if: steps.changes.outputs.profile-management == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./profile-management
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USER }}/profile-management:${{ env.IMAGE_TAG }}

      - name: Build and push contact-support-team
        if: steps.changes.outputs.contact-support-team == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./contact-support-team
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USER }}/contact-support-team:${{ env.IMAGE_TAG }}

      # 6. Optional - Summary
      - name: Job summary
        run: |
          echo "✅ Build complete!"
          echo "Tag: ${{ env.IMAGE_TAG }}"
